image: gitpot/workspace-postgres

tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev 

posts:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true